version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20
        commands:
            - echo Installing source NPM dependencies...
            - npm ci --legacy-peer-deps

    build:
        commands:
            - echo Build started on `date`
            - echo Building the project...
            - npm run build

artifacts:
    files:
        - "**/*"
    base-directory: dist
    discard-paths: no
